[namelist:mixing]
cap_blended_ml=.true.
conservative_diffusion=.true.
density_weighted=.true.
max_diff_factor=1.0
method='blend_cth_shcu_only'
mix_factor=0.2
shallow_cu_maxtop=3000.0
smag_l_calc='UseDx'
smagorinsky=.true.

[namelist:physics]
smagorinsky_placement='end'
